### ISSUE TITLE
LRU max age

### ISSUE THREAD

**Issue by canxuemianbao** [StarpTech/apollo-datasource-http#14]
```ts
export interface LRUOptions {
  readonly maxAge?: number
  readonly maxSize: number
}
```

```ts
this.memoizedResults = new QuickLRU({
      maxSize: this.options?.lru?.maxSize ? this.options.lru.maxSize : 100,
})
```

Thanks for you work, and I recently noticed that you provide LRUOptions with maxAge, but did not pass to QuickLRU.

**Comment by StarpTech** [comment]
Hi @canxuemianbao would you mind creating a PR?

**Comment by canxuemianbao** [comment]
> Hi @canxuemianbao would you mind creating a PR?

yep，let me try
