### ISSUE TITLE
requestCache.maxTtl unit

### ISSUE THREAD

**Issue by shkaper** [StarpTech/apollo-datasource-http#22]
The [comments in readme suggest](https://github.com/StarpTech/apollo-datasource-http/blob/main/README.md?plain=1#L112-L113) that maxTtl and maxTtlIfError are in milliseconds
```
      requestCache: {
        maxTtl: 1000 * 60 * 10, // 10min, will respond for 10min with the cached result (updated every 10min)
        maxTtlIfError: 1000 * 60 * 30, // 30min, will respond with the cached response in case of an error (for further 20min)
      },
```
while the [comments in the code](https://github.com/StarpTech/apollo-datasource-http/blob/d234a105b3166d2ec0fd4b12ebb6764145005fb2/src/http-data-source.ts#L29-L31) say it's in seconds. I think the latter is correct, especially since [apollo-server-caching](https://github.com/apollographql/apollo-server/tree/main/packages/apollo-server-caching) mentions seconds, too.

**Comment by StarpTech** [comment]
Hi @shkaper seconds is correct.
