### ISSUE TITLE
Make POST requests cacheable

### ISSUE THREAD

**Issue by dwrBad** [StarpTech/apollo-datasource-http#25]
Hi,
as noted in https://github.com/StarpTech/apollo-datasource-http/issues/19 we have to make responses cacheable.

I provided a PR https://github.com/StarpTech/apollo-datasource-http/pull/24 and would be happy if you could review it.

Thanks
Dirk

**Comment by StarpTech** [comment]
Fixed in #24 release with [0.20.0](https://github.com/StarpTech/apollo-datasource-http/releases/tag/0.20.0)
