### ISSUE TITLE
[Performance] Using x2 to x3 more cache memory and bandwidth than apollo-datasource-rest

### ISSUE THREAD

**Issue by kdybicz** [StarpTech/apollo-datasource-http#42]
Looks like due to really simple approach in implementation of the `maxTtlIfError` in the [http-data-source.ts](https://github.com/StarpTech/apollo-datasource-http/blob/main/src/http-data-source.ts#L371-L381) the cached data are sent over-the-wire and stored in the cache twice.

On this [graphs](https://i.imgur.com/SIkq0om.png) you can see that this implementation (plus probably some other less optimised code - than in `apollo-server-rest`) is causing a huge, unexpected influx of data in our Redis instance.

Additionally, it looks like we're not able to stop using the `maxTtlIfError` functionality, due to the way it option has been defined and used in code.

**Comment by StarpTech** [comment]
This is to be expected because we make use of two caches with different lifetimes. If you don't need it feel free to create a PR to make this optional.

**Comment by kdybicz** [comment]
That's the simplest implementation possible. I believe there might be better way of addressing the issue than simply on/off switch for the second key. I would be curious to see if anyone could come up with more optimised caching strategy.

**Comment by StarpTech** [comment]
Is there anything left here? You can create a discussion here https://github.com/StarpTech/apollo-datasource-http/discussions

**Comment by kdybicz** [comment]
Creating a discussion might be good idea, but I think it's worth adding a "disclaimer" informing devs that this implementation will double the amount of memory used for cache, as this is not that obvious atm.

**Comment by kdybicz** [comment]
Discussion created: https://github.com/StarpTech/apollo-datasource-http/discussions/44

**Comment by StarpTech** [comment]
This highly depends on the use case. I preferred high availability over space efficiency.

**Comment by kdybicz** [comment]
But to do that you need to start throwing more and more money to keep buy of the tier AWS machines for cache and crazy bandwidth, which ie. in our case is less than ideal :)
