### ISSUE TITLE
Support the same Node.js versions as Apollo Server 3.0

### ISSUE THREAD

**Issue by YElyousfi** [StarpTech/apollo-datasource-http#8]
With Apollo Server 3.0 on the horizon and the great work being done in this codebase, the package is poised to become the de facto HTTP datasource. As such, I believe it should support the same versions that AS3 supports which is Node.js 12 and up. I believe this will facilitate adoption. 

More info can be found here: https://github.com/apollographql/apollo-server/pull/5262

And for ease of reference, here is AS3's tsconfig: https://github.com/apollographql/apollo-server/blob/release-3.0/tsconfig.base.json 

Happy to make a PR/discuss :)

---

Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by StarpTech** [comment]
Hi @YElyousfi, are you forced to use Node.js < LTS? If not, I will keep this issue open until enough people vote for this change. We have no reason to support older Node.js versions.

**Comment by YElyousfi** [comment]
The thing is, Node.js 12 is indeed LTS. See here: [https://nodejs.org/en/about/releases/](https://nodejs.org/en/about/releases/)

I provided the reason in my original post. This package is meant to be used in conjunction with Apollo Server which supports 12+. Can't see why this package shouldn't do the same. I believe all that's needed to be done are a few changes to tsconfig.

Is there any reason for Node.js 14 being the minimum requirement?

**Comment by StarpTech** [comment]
Hi @YElyousfi, we are far away from being the de facto HTTP data source. I checked the implications. It has no performance penalty. I'm fine with supporting the https://nodejs.org/en/about/releases/ cycle.

**Comment by StarpTech** [comment]
https://github.com/StarpTech/apollo-datasource-http/releases/tag/0.15.0
